version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      # Install Python 3.12 if not already installed (modify if using a different version)
      # Upgrade pip to its latest version
      # Install virtualenv
  pre_build:
    commands:
      # Set up virtual environments for each function to isolate dependencies
  build:
    commands:
      # Install dependencies and package the first Lambda function
      - cd LF1
      - zip -r9 ${CODEBUILD_SRC_DIR}/function1.zip lambda_function.py
      # - cd $CODEBUILD_SRC_DIR
      # - zip -g function1.zip lambda_function_1.py # Replace with your actual file name

      # Install dependencies and package the second Lambda function
      - cd ../LF2
      - zip -r9 ${CODEBUILD_SRC_DIR}/function2.zip lambda_function.py
      # - cd $CODEBUILD_SRC_DIR
      # - zip -g function2.zip lambda_function_2.py # Replace with your actual file name
  
  post_build:
    commands:
      - cd ..
      - echo "Updating index-photo lambda function"
      - aws lambda update-function-code --function-name LF1 --zip-file fileb://function1.zip
      - echo "Updating search-photo lambda function"
      - aws lambda update-function-code --function-name LF2 --zip-file fileb://function2.zip
      - echo "post_build step"

artifacts:
  files:
    - function1.zip
    - function2.zip

# Optional: If you need to execute specific commands after the build process is complete
